### ISSUE TITLE
53: a very meta show

### ISSUE THREAD

**Issue by noahcollins** [nodeup/transcriptions#6]
I've started working on this episode. https://github.com/noahcollins/transcriptions/tree/53-a-very-meta-show

Thanks for the awesome podcast!

**Comment by dshaw** [comment]
@noahcollins Fantastic!

Going to rope in @khalifenizar‎ @Nevraeka‎ @cliffano‎ @mattcreager‎ to help resolve who said what.

**Comment by noahcollins** [comment]
@dshaw Excellent. The transcript is going pretty fast - I expect to have a complete rough version ready on Thursday.

**Comment by nizaroni** [comment]
I'll give it a listen later in the week and fill in the names where needed!

**Comment by dshaw** [comment]
@khalifenizar‎ @Nevraeka‎ @cliffano‎ @mattcreager‎ I bet you can spot some of the things you said just by reading the transcript.

**Comment by nizaroni** [comment]
Gave it a quick listen to fill in the current blank names. Sent pull request to @noahcollins repo. Will keep my eye out for updates!

**Comment by dshaw** [comment]
Awesome. Thanks, @khalifenizar.

**Comment by noahcollins** [comment]
@dshaw @khalifenizar‎ @Nevraeka‎ @cliffano‎ @mattcreager‎

Okay, we've got a 99% complete transcript! A few items left.

Specifics: I need help with these.
1. There are a couple untranscribed words or phrases I couldn't interpret. They're denoted with a ---.
2. I've left a few passages without names. I'll fill those in next week if no one else gets to it.
3. The name of "Trello team member who contributed to the realtime show" at 55:54.
4. The name of "local developer Brian ---" at 1:21:20.
5. There's some untranscribed chat from 1:06:21-1:07:30 about the Pair With Me URL. I'll fill it in later.

General
6. ToC items. Thoughts?
7. Parentheticals. I edited, omitted, or re-ordered many parentheticals for readability and concision.
8. F-bombs and such. I omitted the only f-bomb on the show. It involved CoffeeScript, naturally. I can leave the bombs in, always take them out, or just decide based on the tone. Let me know.
9. False starts. I omitted almost all of the short overlaps, false starts, and back-and-forth exchanges unless they moved the dialog forward.

**Comment by dshaw** [comment]
6) ToC. Love it.
7) +1
8) LOL! Go ahead and make the call.
9) Fantastic.

**Comment by dshaw** [comment]
3) @BrettKiefer

**Comment by cliffano** [comment]
I've sent a PR to fill in my --- bits.

Also, not sure how to fix this...
I swear I said "Flickr Photo" :p, but after listening to the recording multiple times, I did incorrectly say "Facebook Photo". Sorry, this is called the 4am side-effect lol.
I was referring to this tweet https://twitter.com/davglass/status/389916493682851841

In the PR I replaced Facebook with Flickr. Pls let me know if there's a better way to put this correction.

**Comment by nizaroni** [comment]
I think it might be useful to clarify intention in footnotes.

**Comment by mattcreager** [comment]
I'll have another listen through tonight and drop in a PR, thanks for
putting together the transcripts they look great :)

**Comment by mattcreager** [comment]
Alright I've dropped in a PR too, I merged most of the stuff around the disconnect... hope that's alright!

**Comment by Nevraeka** [comment]
@khalifenizar-If you need help next week I am available to work on : 

"5. There's some untranscribed chat from 1:06:21-1:07:30 about the Pair With Me URL. I'll fill it in later."

**Comment by nizaroni** [comment]
@Nevraeka I was planning on giving it another listen tonight or tomorrow morning but the more eyes the better. By the way, I'll hit you up on Twitter to pair maybe next week.

**Comment by Nevraeka** [comment]
@khalifenizar sounds like a plan. Let me know how it goes

**Comment by noahcollins** [comment]
@khalifenizar

> I think it might be useful to clarify intention in footnotes.

I like this idea - do you have an example so I can see what you're aiming for?

**Comment by nizaroni** [comment]
I had that in mind for cases like Cliffano's where the speaker may not have been 100% clear or was mistakenly inaccurate. With footnotes we can have editorial clarifications but they won't be interpreted as part of the transcription since nobody talks in footnotes. Something like this, except in a way where markdown would actually treat them as links:

``` md
Blah blah blah ... Facebook photo page [1].

...

// End of transcription
## Footnotes
[1]: Speaker was referring to the Flickr photo page.
```

**Comment by noahcollins** [comment]
@khalifenizar That makes sense to me. Any thoughts on the utility of inline notes vs footnotes? My instinct is that short/simple editorial corrections would be more useful inline, whereas more complex notes would need to be at the end. What do you think?

**Comment by nizaroni** [comment]
@noahcollins I agree with you, so long as inline editor notes are easily distinguishable from what the speaker said. We can try it out to see if that's the case. BTW I'm off today so I'll definitely do a final look over of the transcript today.

**Comment by noahcollins** [comment]
@khalifenizar Excellent! 

That makes sense re: inline notes. I'll try it on the Facebook/Flickr photos section and see how it looks.

**Comment by nizaroni** [comment]
I'm about half-way through the read/listen. Opened https://github.com/noahcollins/transcriptions/pull/6 so you can look over the changes so far. Will finish tomorrow night.

**Comment by nizaroni** [comment]
PR ready! Let me know if you want me to undo anything before merging.

**Comment by noahcollins** [comment]
I think this transcript is ready. Going to submit a pull request.

**Comment by dshaw** [comment]
:+1:

**Comment by nizaroni** [comment]
Did we just finish the first full NodeUp transcription? Cheers, fellas! :beers:  :+1: :+1: :+1:

**Comment by dshaw** [comment]
:clap: :clap: :clap: Solid!

**Comment by noahcollins** [comment]
I think we're good to close this one now.

**Comment by dshaw** [comment]
Now we just need to get transcriptions integrated into the next iteration of the site!
https://github.com/nodeup/contribute/issues/24

/cc @floating
