### ISSUE TITLE
56: A Team Walmart Show #nodebf

### ISSUE THREAD

**Issue by noahcollins** [nodeup/transcriptions#9]
Another awesome teams show! Thanks to the Walmart team for participating. I'm going to start transcribing this one over the weekend.

https://github.com/noahcollins/transcriptions/tree/56-a-team-walmart-show-nodebf

**Comment by nizaroni** [comment]
You are a king among men, @noahcollins. I'd be more than happy to help review (even though I wasn't in this one).

**Comment by noahcollins** [comment]
@khalifenizar likewise! Thanks very much. Any time you can give will be much appreciated.

**Comment by noahcollins** [comment]
@dshaw @khalifenizar Okay, we have one more complete NodeUp transcribed! I've listened through a few times now, so the transcript is in pretty good shape. If anyone else can give it a quick once-over I'd say it's ready to merge.

There is one outstanding item that I haven't resolved. There's a drop out in the call from 56:01-56:06. I'm not sure from context what Eran might have been saying there, so I just marked the hole in the transcript.

**Comment by nizaroni** [comment]
@noahcollins I'll give it a listen over the weekend. Maybe one of the participants would remember the context of what Eran was saying. I'll leave the pinging to @dshaw though. :smiling_imp:

**Comment by noahcollins** [comment]
@khalifenizar Awesome, thanks very much!

**Comment by dshaw** [comment]
Thank you @noahcollins and @khalifenizar. I'm pretty sure @floating lost connection during that gap.

**Comment by dshaw** [comment]
@noahcollins Pull request time?

**Comment by noahcollins** [comment]
Yes. I think it's ready to go in now, even if it's only 99% perfect. Hopefully @khalifenizar doesn't prove me too wrong on that point ;)

**Comment by nizaroni** [comment]
@noahcollins I haven't found the time to review yet, but if you are confident I think we are okay to merge. I can make an additional pull request after the fact on the off chance there are adjustments.

**Comment by noahcollins** [comment]
Sounds great!

**Comment by noahcollins** [comment]
Closing this issue now that the transcript is merged.
